# Database Connection
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/stackoverflow?allowPublicKeyRetrieval=true&useSSL=false
#    username: root
#    password: root
#
## Repository
#repository-type: JDBC
#
## Server
#server:
#  port: 8081
#
